---
# handlers file for ansible-network.config_store
#
- name: commit local changes
  git_commit:
    repo: "{{ config_store_working_dir }}"
  run_once: yes

- name: push local to remote
  git_push:
    repo: "{{ config_store_working_dir }}"
  run_once: yes

- name: remove local repo
  file:
    path: "{{ config_store_working_dir }}"
    state: absent
  run_once: yes
